Crm.DynamicForms/ViewModels/ResponseViewModel.cs
namespace Crm.DynamicForms.ViewModels
{
	using Crm.DynamicForms.Model;
	using Crm.Library.AutoFac;
	
	public interface IResponseViewModel<TDynamicFormReference> : IResponseViewModel
		where TDynamicFormReference : DynamicFormReference
	{
		TDynamicFormReference DynamicFormReference { get; set; }
	}
	public interface IResponseViewModel : ITransientDependency
	{
		double HeaderContentSize { get; }
		double HeaderContentSpacing { get; }
		double FooterContentSize { get; }
		double FooterContentSpacing { get; }
	}
}

Crm.DynamicForms/Controllers/DynamicFormController.cs
namespace Crm.DynamicForms.Controllers
{
	using System;
	using System.Collections.Generic;
	using System.Globalization;
	using System.IO;
	using System.Linq;
	using System.Text;
	using AutoMapper;
	using Crm.Controllers;
	using Crm.DynamicForms.Model;
	using Crm.DynamicForms.Model.BaseModel;
	using Crm.DynamicForms.Model.Extensions;
	using Crm.DynamicForms.Model.Lookups;
	using Crm.DynamicForms.Rest.Model;
	using Crm.DynamicForms.Services;
	using Crm.DynamicForms.ViewModels;
	using Crm.Library.AutoFac;
	using Crm.Library.Data.Domain.DataInterfaces;
	using Crm.Library.Extensions;
	using Crm.Library.Globalization.Lookup;
	using Crm.Library.Globalization.Resource;
	using Crm.Library.Helper;
	using Crm.Library.Model;
	using Crm.Library.Model.Authorization.PermissionIntegration;
	using Crm.Library.Modularization;
	using Crm.Library.Rest;
	using Crm.Library.Services.Interfaces;
	using Crm.Model;
	using Crm.Rest.Model;
	using Crm.Results;
	using Crm.Services;
	using Crm.Services.Interfaces;
	using Crm.ViewModels;
	using Microsoft.AspNetCore.Authorization;
	using Microsoft.AspNetCore.Http;
	using Microsoft.AspNetCore.Mvc;

	public class DynamicFormController : CrmController
	{
		private readonly IRepositoryWithTypedId<DynamicForm, Guid> dynamicFormRepository;
		private readonly IRepositoryWithTypedId<FileResource, Guid> fileResourceRepository;
		private readonly IRepositoryWithTypedId<DynamicFormReference, Guid> dynamicFormReferenceRepository;
		private readonly IEnumerable<Lazy<Func<DynamicFormReference, IResponseViewModel>, DependencyMetadata>> responseViewModelFactories;
		private readonly IPdfService pdfService;
		private readonly IDynamicFormElementTypeProvider dynamicFormElementTypeProvider;
		private readonly IUserService userService;
		private readonly IRepositoryWithTypedId<DynamicFormLanguage, Guid> dynamicFormLanguageRepository;
		private readonly IRestSerializer restSerializer;
		private readonly RestTypeProvider restTypeProvider;
		private readonly IRepositoryWithTypedId<DynamicFormElement, Guid> dynamicFormElementRepository;
		private readonly IRepositoryWithTypedId<DynamicFormElementRule, Guid> dynamicFormElementRuleRepository;
		private readonly IRepositoryWithTypedId<DynamicFormElementRuleCondition, Guid> dynamicFormElementRuleConditionRepository;
		private readonly IRepository<DynamicFormLocalization> dynamicFormLocalizationRepository;
		private readonly IRepositoryWithTypedId<DynamicFormResponse, Guid> dynamicFormResponseRepository;
		private readonly IMapper mapper;
		private readonly Func<DynamicFormResponse> dynamicFormResponseFactory;
		private readonly Func<DynamicFormReference> dynamicFormReferenceFactory;
		private readonly Func<DynamicFormLanguage> dynamicFormLanguageFactory;
		private readonly Func<DynamicFormLocalization> dynamicFormLocalizationFactory;
		private readonly IFileService fileService;
		private readonly IRuleValidationService ruleValidationService;
		private readonly IRepositoryWithTypedId<DynamicFormFileResponse, Guid> dynamicFormFileResponseRepository;
		private readonly ILookupManager lookupManager;
		private readonly IResourceManager resourceManager;

		public DynamicFormController(IPdfService pdfService, RestTypeProvider restTypeProvider, IRenderViewToStringService renderViewToStringService, ILookupManager lookupManager, IResourceManager resourceManager, IRuleValidationService ruleValidationService, IRepositoryWithTypedId<DynamicForm, Guid> dynamicFormRepository, IRepositoryWithTypedId<DynamicFormReference, Guid> dynamicFormReferenceRepository, IEnumerable<Lazy<Func<DynamicFormReference, IResponseViewModel>, DependencyMetadata>> responseViewModelFactories, IDynamicFormElementTypeProvider dynamicFormElementTypeProvider, IUserService userService, IRepositoryWithTypedId<DynamicFormLanguage, Guid> dynamicFormLanguageRepository, IRestSerializer restSerializer, IRepositoryWithTypedId<DynamicFormElement, Guid> dynamicFormElementRepository, IMapper mapper, Func<DynamicFormResponse> dynamicFormResponseFactory, Func<DynamicFormReference> dynamicFormReferenceFactory, Func<DynamicFormLanguage> dynamicFormLanguageFactory, Func<DynamicFormLocalization> dynamicFormLocalizationFactory, IRepositoryWithTypedId<DynamicFormElementRule, Guid> dynamicFormElementRuleRepository, IRepositoryWithTypedId<DynamicFormElementRuleCondition, Guid> dynamicFormElementRuleConditionRepository, IRepository<DynamicFormLocalization> dynamicFormLocalizationRepository, IRepositoryWithTypedId<DynamicFormResponse, Guid> dynamicFormResponseRepository, IRepositoryWithTypedId<FileResource, Guid> fileResourceRepository, IRepositoryWithTypedId<DynamicFormFileResponse, Guid> dynamicFormFileResponseRepository, IFileService fileService)
			: base(pdfService, renderViewToStringService)
		{
			this.dynamicFormRepository = dynamicFormRepository;
			this.dynamicFormReferenceRepository = dynamicFormReferenceRepository;
			this.responseViewModelFactories = responseViewModelFactories;
			this.pdfService = pdfService;
			this.restTypeProvider = restTypeProvider;
			this.lookupManager = lookupManager;
			this.resourceManager = resourceManager;
			this.ruleValidationService = ruleValidationService;
			this.dynamicFormElementTypeProvider = dynamicFormElementTypeProvider;
			this.userService = userService;
			this.dynamicFormLanguageRepository = dynamicFormLanguageRepository;
			this.restSerializer = restSerializer;
			this.dynamicFormElementRepository = dynamicFormElementRepository;
			this.mapper = mapper;
			this.dynamicFormResponseFactory = dynamicFormResponseFactory;
			this.dynamicFormReferenceFactory = dynamicFormReferenceFactory;
			this.dynamicFormLanguageFactory = dynamicFormLanguageFactory;
			this.dynamicFormLocalizationFactory = dynamicFormLocalizationFactory;
			this.dynamicFormElementRuleRepository = dynamicFormElementRuleRepository;
			this.dynamicFormElementRuleConditionRepository = dynamicFormElementRuleConditionRepository;
			this.dynamicFormLocalizationRepository = dynamicFormLocalizationRepository;
			this.dynamicFormResponseRepository = dynamicFormResponseRepository;
			this.dynamicFormFileResponseRepository = dynamicFormFileResponseRepository;
			this.fileService = fileService;
			this.fileResourceRepository = fileResourceRepository;
		}
		public virtual ActionResult DisplayTemplates()
		{
			var elementTypeNames = dynamicFormElementTypeProvider.ElementTypes.Keys.ToList();
			var model = new CrmModelList<string> { List = elementTypeNames };
			return PartialView(model);
		}

		[RenderAction("DynamicFormItemTemplateActions", Priority = 100)]
		[RequiredPermission(PermissionName.Edit, Group = DynamicFormsPlugin.PermissionGroup.DynamicForms)]
		public virtual ActionResult ItemTemplateActionEdit()
		{
			return PartialView();
		}

		[RenderAction("DynamicFormItemTemplateActions", Priority = 90)]
		[RequiredPermission(PermissionName.Delete, Group = DynamicFormsPlugin.PermissionGroup.DynamicForms)]
		public virtual ActionResult ItemTemplateActionDelete()
		{
			return PartialView();
		}

		public virtual ActionResult EditorTemplates()
		{
			var elementTypeNames = dynamicFormElementTypeProvider.ElementTypes.Keys.ToList();
			var model = new CrmModelList<string> { List = elementTypeNames };
			return PartialView(model);
		}

		public virtual ActionResult MaterialEditorTemplates()
		{
			var elementTypeNames = dynamicFormElementTypeProvider.ElementTypes.Keys.ToList();
			var model = new CrmModelList<string> { List = elementTypeNames };
			return PartialView(model);
		}

		[RenderAction("FormDesignerSidebarTabContent", Priority = 100)]
		public virtual ActionResult FormDesignerSidebarTabContentAddFields()
		{
			return PartialView();
		}

		[RenderAction("FormDesignerSidebarTabHeader", Priority = 100)]
		public virtual ActionResult FormDesignerSidebarTabHeaderAddFields()
		{
			return PartialView();
		}

		[RenderAction("FormDesignerSidebarTabContent", Priority = 90)]
		public virtual ActionResult FormDesignerSidebarTabContentEditField()
		{
			return PartialView();
		}

		[RenderAction("FormDesignerSidebarTabHeader", Priority = 90)]
		public virtual ActionResult FormDesignerSidebarTabHeaderEditField()
		{
			return PartialView();
		}

		[RenderAction("FormDesignerSidebarTabContent", Priority = 80)]
		public virtual ActionResult FormDesignerSidebarTabContentEditForm()
		{
			return PartialView();
		}

		[RenderAction("FormDesignerSidebarTabHeader", Priority = 80)]
		public virtual ActionResult FormDesignerSidebarTabHeaderEditForm()
		{
			return PartialView();
		}

		public virtual ActionResult FormElementRuleEditor()
		{
			return PartialView();
		}

		[RenderAction("MaterialHeadResource", Priority = 6990)]
		public virtual ActionResult HeadResource()
		{
			return Content(Url.JsResource("Crm.DynamicForms", "dynamicFormsMaterialJs") + Url.JsResource("Crm.DynamicForms", "dynamicFormsMaterialTs"));
		}

		[RenderAction("MaterialTitleResource", Priority = 6990)]
		public virtual ActionResult TitleResource()
		{
			return Content(Url.CssResource("Crm.DynamicForms", "dynamicFormsMaterialCss"));
		}

		[HttpPost]
		public virtual ActionResult Import(IFormFile jsonFile)
		{
			DynamicFormExport dynamicFormExport;
			using (var memoryStream = new MemoryStream())
			{
				jsonFile.OpenReadStream().CopyTo(memoryStream);
				byte[] data = memoryStream.ToArray();
				var json = Encoding.UTF8.GetString(data);
				try
				{
					dynamicFormExport = (DynamicFormExport)restSerializer.Parse(json, typeof(DynamicFormExport));
				}
				catch
				{
					return new JsonResult(new { Guid.Empty });
				}
			}

			var dynamicForm = mapper.Map<DynamicForm>(dynamicFormExport.DynamicForm);
			dynamicForm.Id = Guid.Empty;
			dynamicForm.AuthData = null;
			dynamicFormRepository.SaveOrUpdate(dynamicForm);
			foreach (var dynamicFormLanguageRest in dynamicFormExport.Languages)
			{
				var dynamicFormLanguage = mapper.Map<DynamicFormLanguage>(dynamicFormLanguageRest);
				dynamicFormLanguage.DynamicFormKey = dynamicForm.Id;

Crm.DynamicForms/Views/DynamicForm/DesignerAddField.cshtml
@inherits Crm.Library.Modularization.CrmViewUserControl<Crm.ViewModels.CrmModel>
@using Crm.Library.Globalization.Extensions

<!--ko if: isPdf() === false-->
<div id="add-fields" class="box ptpx15">
    <div class="entry clearfix elementTypes no-border">
        <div class="alert alert-danger" style="display: none" data-bind="visible: Helper.DynamicFormDesigner.displayAlreadyReleasedWarning($root.alreadySavedDynamicForm())">@(Html.Localize("DynamicFormAlreadyReleasedWarning"))</div>
        <!-- ko foreach: formElementTypes -->
        <div class="pager " data-bind="draggable: { data: $data, helper: 'clone' }, visible: isVisible">
            <a class="btn btn-default btn-sm" href="#" data-bind="translatedText: FormElementType"></a>
        </div>
        <!-- /ko -->
    </div>
</div>
<!-- /ko -->


<!--ko if: isPdf() === true-->
<div class="box ptpx15">
    <div class="entry clearfix elementTypes no-border">
        <div class="alert alert-danger" style="display: none">@(Html.Localize("DynamicFormAlreadyReleasedWarning"))</div>
        <p data-bind="visible: $root.pageCount() == 0">@(Html.Localize("PdfUploadRequired"))</p>
        <div class="form-group">
            <input id="uploadPdf" class="form-control" type="file" data-bind="event: {change: $root.handlePdfUpload.bind($root)}" accept=".pdf"/>
        </div>
    </div>
</div>
<!-- /ko -->

Crm.DynamicForms/Views/DynamicForm/DesignerEditField.cshtml
@inherits Crm.Library.Modularization.CrmViewUserControl<Crm.ViewModels.CrmModel>
@using Crm.Library.Extensions
@using Crm.Library.Globalization.Extensions
<div class="box ptpx15">
	<div class="entry clearfix no-border" data-bind="visible: Helper.DynamicFormDesigner.displayAlreadyReleasedWarning($root.alreadySavedDynamicForm())">
		<div class="alert alert-danger">@(Html.Localize("DynamicFormAlreadyReleasedWarning"))</div>
	</div>
	<div id="editFieldBox" class=" entry clearfix entry no-border"  data-bind="visible: !selectedFormElement()">
		@(Html.Localize("DynamicFormEditFieldEmptySlate"))
	</div>
	<div class="entry clearfix no-border"  data-bind="visible: selectedFormElement()">
		<!-- ko if: selectedFormElement -->
			<!-- ko with: selectedFormElement -->
				@Html.RenderAction("EditorTemplates", "DynamicForm", new { plugin = "Crm.DynamicForms" })
			<!-- /ko -->
		<!-- /ko -->
	</div>
</div>

Crm.DynamicForms/Views/DynamicForm/DynamicFormPageFooter.cshtml
@inherits Crm.Library.Modularization.CrmViewPage
@{Layout = "~/Views/Shared/Layout/HtmlTemplateLayout.cshtml";}

@section TemplateMainContent {

	<div class="reportcontainer">
		<div class="report">
			 @await Html.PartialAsync("Report/FooterContent") 
		</div>
	</div>

}

Crm.DynamicForms/Views/DynamicForm/DynamicFormPageHeader.cshtml
@inherits Crm.Library.Modularization.CrmViewPage
@{Layout = "~/Views/Shared/Layout/HtmlTemplateLayout.cshtml";}

@section TemplateMainContent {

	<div class="reportcontainer">
		<div class="report">
			 @await Html.PartialAsync("Report/HeaderContent") 
		</div>
	</div>

}

Crm.DynamicForms/Views/DynamicForm/FormDesignerSidebarTabContentAddFields.cshtml
<div role="tabpanel" class="tab-pane animated fadeIn m-20" id="tab-add-fields">
    <div data-bind="visible: $root.form().CategoryKey() =='PDF-Checklist'">
        <div class="form-group">
            <div class="fileinput" data-provides="fileinput" data-bind="css: { 'fileinput-exists': $root.currentFileResource() !== null, 'fileinput-new': $root.currentFileResource() == null }">
					<div>
							<span class="btn btn-lg btn-primary f-13 btn-file waves-effect">
							<span class="fileinput-new">Select File</span>
							<span class="fileinput-exists">Change</span>
							<input id="uploadPdf" type="file" accept=".pdf" data-bind="fileInput: { content: $root.currentFileResource() !== null ? $root.currentFileResource().Content() : '' }, event: {change: $root.uploadPdf.bind($root)}">
						</span>
			            <span data-bind="text: $root.currentFileResource() !== null ? $root.currentFileResource().Filename() : ''"></span>
                        <a href="#" class="close fileinput-exists" data-dismiss="fileinput">×</a>
					</div>
			</div>
        </div>
    </div>
    <div class="row" data-bind="visible: $root.form().CategoryKey() !=='PDF-Checklist' ">
        <!-- ko foreach: formElementTypes -->
        <!-- ko if: ($data.FormElementType() && $data.FormElementType() !== 'SignaturePadWithPrivacyPolicy') || window.Crm.DynamicForms.Settings.DynamicFormElement.SignaturePad.Show.PrivacyPolicy -->
        <span data-bind="draggable: { data: $data, helper: 'clone' }" class="col-md-6 p-10">
            <a class="btn btn-default btn-lg btn-block f-13" data-bind="translatedText: FormElementType, click: $root.showHintToast"></a>
        </span>
        <!-- /ko -->
        <!-- /ko -->
    </div>
</div>

Crm.DynamicForms/Views/DynamicForm/FormDesignerSidebarTabContentEditForm.cshtml
@inherits Crm.Library.Modularization.CrmViewUserControl
@using Crm.Library.Globalization.Extensions
<div role="tabpanel" class="tab-pane animated fadeIn m-20" id="tab-edit-form">
	<fieldset>
		<legend class="m-b-25 c-black b-0 f-500 f-14" data-bind="translatedText: 'DynamicForm'"></legend>
		<div class="form-group" data-bind="validationElement: $root.getLocalization().Value, validationOptions: { insertMessages: false }">
			<div data-bind="css: { 'input-group': $root.form().Languages().length > 1 }">
				<div class="fg-line">
					<label class="fg-label control-label">
						<span class="description" data-bind="translatedText: 'Title'"></span>
					</label>
					<input class="form-control" data-bind="textInput: $root.getLocalization().Value" id="Title" name="Title" type="text"/>
				</div>
				<span class="input-group-addon" data-bind="visible: $root.form().Languages().length > 1">
					<a class="btn btn-default btn-icon waves-effect waves-circle waves-float" href="#" data-bind="click: () => $root.editLocalizations(null, null, false), tooltip: true" title="@(Html.Localize("Translations"))">
						<i class="zmdi zmdi-globe"></i>
					</a>
				</span>
			</div>
		</div>
		<div class="form-group" data-bind="validationElement: $root.getLocalization().Hint, validationOptions: { insertMessages: false }">
			<div data-bind="css: { 'input-group': $root.form().Languages().length > 1 }">
				<div class="fg-line">
					<label class="fg-label control-label">
						<span class="description" data-bind="translatedText: 'Description'"></span>
					</label>
					<textarea class="form-control" data-bind="value: $root.getLocalization().Hint, autosize: true" id="Hint" name="Hint"></textarea>
				</div>
				<span class="input-group-addon" data-bind="visible: $root.form().Languages().length > 1">
					<a class="btn btn-default btn-icon waves-effect waves-circle waves-float" href="#" data-bind="click: () => $root.editLocalizations(null, null, true), tooltip: true" title="@(Html.Localize("Translations"))">
						<i class="zmdi zmdi-globe"></i>
					</a>
				</span>
			</div>
		</div>
		<form-element params="value: $root.form().HideEmptyOptional, caption:'HideEmptyOptional', type: 'checkbox'"></form-element>
	</fieldset>
	<fieldset>
		<legend class="p-t-25 m-b-25 c-black b-0 f-500 f-14" data-bind="translatedText: 'Translations'"></legend>
		<form-element params="value: newLanguageKey, caption: 'Language', type: 'select'">
			<select class="form-control" data-bind="select2autocompleter: { data: value, autocompleteOptions: Helper.Lookup.getAutocompleteOptions('Main_Language'), placeholder: placeholder }">
			</select>
		</form-element>
		<button class="btn btn-primary waves-effect" data-bind="translatedText: 'Add', click: addLanguage"></button>
		<hr />
		<table class="table">
			<thead>
			<tr>
				<th data-bind="translatedText: 'Language'"></th>
				<th data-bind="translatedText: 'Status'"></th>
				<th data-bind="translatedText: 'IsDefault'"></th>
				<th></th>
			</tr>
			</thead>
			<tbody data-bind="foreach: $root.form().Languages">
			<tr>
				<td data-bind="text: $root.languages()[$data.LanguageKey()].Value"></td>
				<td>
					<form-element params="value: StatusKey, type: 'select'">
						<select class="form-control status-key" data-bind="options: $root.statuses, optionsValue: 'Key', optionsText: 'Value', value: value"></select>
					</form-element>
				</td>
				<td>
					<label class="radio">
						<input type="radio" name="DefaultLanguageKey" data-bind="checked: $root.form().DefaultLanguageKey, checkedValue: LanguageKey, enable: StatusKey() === 'Released'"/>
						<i class="input-helper"></i>
					</label>
				</td>
				<td>
					<button class="btn btn-danger btn-sm waves-effect" data-bind="click: $root.removeLanguage, tooltip: true" title="@Html.Localize("Remove")">
						<i class="zmdi zmdi-hc-lg zmdi-delete"></i>
					</button>
				</td>
			</tr>
			</tbody>
		</table>
	</fieldset>
</div>

Crm.DynamicForms/Views/DynamicForm/FormDesignerSidebarTabHeaderEditField.cshtml
<li role="presentation" data-bind="visible: $root.form().CategoryKey() !=='PDF-Checklist'">
	<a class="col-xs-4 p-b-0" href="#tab-edit-field" aria-controls="tab-edit-field" role="tab" data-toggle="tab" aria-expanded="false">
		<i class="zmdi zmdi-edit zmdi-hc-2x"></i>
		<h6 data-bind="translatedText: 'EditField'"></h6>
	</a>
</li>

Crm.DynamicForms/Views/DynamicForm/FormDesignerSidebarTabHeaderEditForm.cshtml
<li role="presentation">
	<a class="col-xs-4 p-b-0" href="#tab-edit-form" aria-controls="tab-edit-form" role="tab" data-toggle="tab" aria-expanded="false">
		<i class="zmdi zmdi-settings zmdi-hc-2x"></i>
		<h6 data-bind="translatedText: 'EditForm'"></h6>
	</a>
</li>

Crm.DynamicForms/Views/DynamicForm/ImportModal.cshtml
@inherits Crm.Library.Modularization.CrmViewUserControl
@using Crm.Library.Globalization.Extensions

<div class="modal fade" id="dynamic-form-import-modal" tabindex="-1" role="dialog">
	<form id="dynamic-form-import-form" action="@(Url.Action("Import", "DynamicForm", new { plugin = "Crm.DynamicForms" }))" method="post">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">@(Html.Localize("ImportFile"))</h4>
				</div>
				<div class="modal-body card-body card-padding">
					<div class="form-group">
						<label class="field">
							<span class="description">@(Html.Localize("ImportFile")) (json)</span>
						</label>
						<input class="form-control" name="jsonFile" type="file">
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">@(Html.Localize("Cancel"))</button>
					<input type="submit" class="btn btn-primary" value="@(Html.Localize("ImportFile"))" />
				</div>
			</div>
		</div>
	</form>
</div>

Crm.DynamicForms/Views/DynamicForm/ItemTemplateActionDelete.cshtml
<li data-bind="visible: Languages().some(x => x.StatusKey() !== 'Disabled')">
	<a class="delete" href="#" data-bind="click: $root.remove, translatedText: 'Delete'"></a>
</li>

Crm.DynamicForms/Views/DynamicForm/ItemTemplateActionEdit.cshtml
@inherits Crm.Library.Modularization.CrmViewUserControl

<li>
	<a href="#/Crm.DynamicForms/DynamicForm/EditTemplate/{{Id}}" data-bind="translatedText: 'Edit'"></a>
</li>

Crm.DynamicForms/Views/DynamicForm/Response.cshtml
@inherits Crm.Library.Modularization.CrmViewPage
@{Layout = "~/Views/Shared/Layout/HtmlTemplateLayout.cshtml";}
@using Crm.Extensions
@using Crm.Library.Extensions
@using Crm.Library.Modularization.Extensions
@using Crm.Offline.Extensions

@section TemplateMainContent {

	@(Html.JsResource("jayDataJs"))
	@await Html.PartialAsync("Report/Header")
	@using (Html.TemplateContext("$root.DynamicForm")){
		<h1 class="text-right" data-bind="text: $root.getLocalizationText(null)"></h1>
		<h4 class="text-right c-gray" data-bind="text: window.Helper.DynamicForm.getDescription($root.DynamicForm(), $root.localizations(), $root.selectedLanguage())"></h4>
		<div class="dynamic-form-response-header">
			@Html.PluginRenderActions("DynamicFormResponseHeader")
		</div>
		@using (Html.TemplateForEach("$root.groupedElements()")){
			<div class="section">
				@using (Html.TemplateForEach("$data")){
					<div class="row elementgroup">
						@using (Html.TemplateForEach("$data")){
							<div data-bind="css: 'form-element col-xs-' + 12 / $data.Size() + ' form-element-' + $data.FormElementType().toLowerCase(), visible: $root.showInResponse($data)">
								@Html.RenderAction("ResponseTemplates", "DynamicForm", new { plugin = "Crm.DynamicForms" })
							</div>
						}
					</div>
				}
			</div>
		}
	 }
	<div class="dynamic-form-response-footer">
		@Html.PluginRenderActions("DynamicFormResponseFooter")
	</div>
	@using (Html.TemplateContext("$root.DynamicForm")){
		<div data-bind="visible: $root.elements().indexOf(window.ko.utils.arrayFirst($root.elements(), function (element) { return element.FormElementType() === 'SignaturePadWithPrivacyPolicy' && (!!element.Required && element.Required() == true || $root.DynamicForm().HideEmptyOptional() == false || $root.DynamicForm().HideEmptyOptional() == true && !!element.Required && element.Required() == false && (element.Response() != null && element.Response() != '' && ko.toJSON(element.Response) != element.DefaultResponseValue())); })) > -1">
			 @await Html.PartialAsync("DataPrivacyPolicy")
		</div>
	}
	@await Html.PartialAsync("Report/Footer")
}

Crm.DynamicForms/Views/DynamicForm/Title.cshtml
@inherits Crm.Library.Modularization.CrmViewUserControl<Crm.ViewModels.CrmModel>

<title data-bind="text: $root.getLocalizationText(null)"></title>

Crm.DynamicForms/Views/DynamicForm/ViewModel.cshtml
@inherits Crm.Library.Modularization.CrmViewUserControl<IResponseViewModel>
@using Crm.DynamicForms.ViewModels

@{  var model = Model as IResponseViewModel;
	if (model != null) { 
	var restModel = RestTypeProvider.CreateRestModel(model);
	var serializedModel = RestSerializer.SerializeAsJson(restModel).Replace(@"\", @"\\").Replace(@"'", @"\'");
	<script type="text/javascript">
		window.viewModelJson = '@(serializedModel)';
	</script>
 } }